# Generated by Django 2.2.14 on 2020-12-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0042_auto_20201204_2223'),
        ('database', '0039_apikey_readable_name'),
    ]

    operations = [
    ]
