# Generated by Django 2.2.14 on 2021-01-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_auto_20210121_0301'),
        ('database', '0044_auto_20210121_0450'),
    ]

    operations = [
    ]
